export const africanCountries: { [code: string]: string }[] = [
  { 'dz': 'Algeria' },
  { 'ao': 'Angola' },
  { 'bj': 'Benin' },
  { 'bw': 'Botswana' },
  { 'bf': 'Burkina Faso' },
  { 'bi': 'Burundi' },
  { 'cm': 'Cameroon' },
  { 'cv': 'Cape Verde' },
  { 'cf': 'Central African Republic' },
  { 'td': 'Chad' },
  { 'km': 'Comoros' },
  { 'cd': 'Congo (Democratic Republic)' },
  { 'cg': 'Congo (Republic)' },
  { 'ci': "Côte d'Ivoire" },
  { 'dj': 'Djibouti' },
  { 'eg': 'Egypt' },
  { 'gq': 'Equatorial Guinea' },
  { 'er': 'Eritrea' },
  { 'sz': 'Eswatini' },
  { 'et': 'Ethiopia' },
  { 'ga': 'Gabon' },
  { 'gm': 'Gambia' },
  { 'gh': 'Ghana' },
  { 'gn': 'Guinea' },
  { 'gw': 'Guinea-Bissau' },
  { 'ke': 'Kenya' },
  { 'ls': 'Lesotho' },
  { 'lr': 'Liberia' },
  { 'ly': 'Libya' },
  { 'mg': 'Madagascar' },
  { 'mw': 'Malawi' },
  { 'ml': 'Mali' },
  { 'mr': 'Mauritania' },
  { 'mu': 'Mauritius' },
  { 'yt': 'Mayotte' },
  { 'ma': 'Morocco' },
  { 'mz': 'Mozambique' },
  { 'na': 'Namibia' },
  { 'ne': 'Niger' },
  { 'ng': 'Nigeria' },
  { 're': 'Réunion' },
  { 'rw': 'Rwanda' },
  { 'st': 'São Tomé and Príncipe' },
  { 'sn': 'Senegal' },
  { 'sc': 'Seychelles' },
  { 'sl': 'Sierra Leone' },
  { 'so': 'Somalia' },
  { 'za': 'South Africa' },
  { 'ss': 'South Sudan' },
  { 'sd': 'Sudan' },
  { 'tz': 'Tanzania' },
  { 'tg': 'Togo' },
  { 'tn': 'Tunisia' },
  { 'ug': 'Uganda' },
  { 'eh': 'Western Sahara' },
  { 'zm': 'Zambia' },
  { 'zw': 'Zimbabwe' },
];

export function getIsoCodeFromCountryName(countryName: string): string | undefined {
  const entry = africanCountries.find(
    country => Object.values(country)[0].toLowerCase() === countryName.trim().toLowerCase()
  );
  return entry ? Object.keys(entry)[0] : undefined;
}
